const sampleData = {
  data: [
    {
      id: 278819,
      common_name: "Crown of thorns",
      slug: "koeberlinia-spinosa",
      scientific_name: "Koeberlinia spinosa",
      year: 1832,
      bibliography: "Flora 15(2 Beibl.): 74 (1832)",
      author: "Zucc.",
      status: "accepted",
      rank: "species",
      family_common_name: null,
      genus_id: 12915,
      image_url:
        "https://bs.plantnet.org/image/o/ac76efb3554a8a682e2ca880adb63ca686e6e95b",
      synonyms: [],
      genus: "Koeberlinia",
      family: "Koeberliniaceae",
      links: {
        self: "/api/v1/species/koeberlinia-spinosa",
        plant: "/api/v1/plants/koeberlinia-spinosa",
        genus: "/api/v1/genus/koeberlinia",
      },
    },
    {
      id: 124010,
      common_name: "Christ's-thorn",
      slug: "paliurus-spina-christi",
      scientific_name: "Paliurus spina-christi",
      year: 1768,
      bibliography: "Gard. Dict. ed. 8: s.p. (1768)",
      author: "Mill.",
      status: "accepted",
      rank: "species",
      family_common_name: null,
      genus_id: 6462,
      image_url:
        "https://bs.plantnet.org/image/o/9561b352a55671f360660808aa40d69cd5968ca5",
      synonyms: [
        "Paliurus microcarpus",
        "Paliurus petasus",
        "Paliurus vulgaris",
        "Paliurus trinervatus",
        "Rhamnus australis",
        "Paliurus spina-christi var. macrocarpus",
        "Paliurus spina-christi var. rotundifolius",
        "Paliurus clypeiformis",
        "Paliurus solitarius",
        "Paliurus spina-christi var. apterus",
        "Rhamnus horrida",
        "Rhamnus paliurus",
        "Paliurus paliurus",
        "Paliurus spina-christi var. inermis",
        "Paliurus aculeatus var. inermis",
        "Ziziphus paliurus",
        "Paliurus australis",
        "Paliurus aculeatus",
        "Paliurus incurvus",
      ],
      genus: "Paliurus",
      family: "Rhamnaceae",
      links: {
        self: "/api/v1/species/paliurus-spina-christi",
        plant: "/api/v1/plants/paliurus-spina-christi",
        genus: "/api/v1/genus/paliurus",
      },
    },
    {
      id: 256204,
      common_name: "Christ's-plant",
      slug: "euphorbia-milii",
      scientific_name: "Euphorbia milii",
      year: 1826,
      bibliography: "Bull. Hist. Nat. Soc. Linn. Bordeaux 1:27.  1826",
      author: "Des Moul.",
      status: "accepted",
      rank: "species",
      family_common_name: null,
      genus_id: 5545,
      image_url:
        "https://bs.plantnet.org/image/o/0335a2d232b6113c84aab00c08a94cdd53e66696",
      synonyms: [
        "Euphorbia milii var. breonii",
        "Euphorbia milii f. lutea",
        "Tumalis bojeri",
        "Euphorbia splendens var. bojeri",
        "Euphorbia bojeri var. mucronulata",
        "Euphorbia breonii",
        "Sterigmanthe bojeri",
        "Euphorbia splendens subsp. bojeri",
        "Euphorbia bojeri",
        "Euphorbia milii var. milii",
      ],
      genus: "Euphorbia",
      family: "Euphorbiaceae",
      links: {
        self: "/api/v1/species/euphorbia-milii",
        plant: "/api/v1/plants/euphorbia-milii",
        genus: "/api/v1/genus/euphorbia",
      },
    },
  ],
  links: {
    self: "/api/v1/plants/search?q=crown+of+thorns",
    first: "/api/v1/plants/search?page=1&q=crown+of+thorns",
    last: "/api/v1/plants/search?page=1&q=crown+of+thorns",
  },
  meta: {
    total: 3,
  },
};

export default sampleData;
